server.port=8080
spring.application.name=ecommerce-logs

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/logdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Log level
logging.level.com.example.ecommerce_logs=INFO
